//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRegistrationApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string YearIssue { get; set; }
        public int Mileage { get; set; }
        public decimal Price { get; set; }
        public string Photos { get; set; }
    }
}
